/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataBukuController;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author lenovo
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    DataBukuController dc;
    public MainView() {
        initComponents();
        dc = new DataBukuController(this);
        dc.isiGenre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDatabuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtjudul = new javax.swing.JTextField();
        jTxtid = new javax.swing.JTextField();
        jTxtgenre = new javax.swing.JTextField();
        jTxtpenulis = new javax.swing.JTextField();
        jTxtpenerbit = new javax.swing.JTextField();
        jTxtlokasi = new javax.swing.JTextField();
        jTxtstock = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        listgenre = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        searchBy = new javax.swing.JComboBox<>();
        jTextsearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelDatabuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "judul", "genre", "penulis", "penerbit", "lokasi", "stock"
            }
        ));
        tabelDatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDatabukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDatabuku);

        jLabel1.setText("ID");

        jLabel2.setText("JUDUL BUKU");

        jLabel3.setText("GENRE BUKU");

        jLabel4.setText("PENULIS BUKU");

        jLabel5.setText("PENERBIT BUKU");

        jLabel6.setText("LOKASI BUKU");

        jLabel7.setText("STOCK BUKU");

        jTxtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtjudulActionPerformed(evt);
            }
        });

        jTxtid.setEditable(false);
        jTxtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtidActionPerformed(evt);
            }
        });

        jTxtgenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtgenreActionPerformed(evt);
            }
        });

        jTxtpenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtpenulisActionPerformed(evt);
            }
        });

        jTxtpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtpenerbitActionPerformed(evt);
            }
        });

        jTxtlokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtlokasiActionPerformed(evt);
            }
        });

        jTxtstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtstockActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnTampil.setText("Tampilkan Semua");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        listgenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listgenre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listgenreItemStateChanged(evt);
            }
        });

        jLabel8.setText("GENRE :");

        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Penulis", "Penerbit" }));

        jTextsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextsearchActionPerformed(evt);
            }
        });

        jLabel10.setText("Cari Buku");

        btnReset.setText("Reset Form");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtlokasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jTxtpenerbit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtpenulis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtgenre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtjudul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtstock))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCari))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(listgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUbah))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTxtgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTxtpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTampil))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTxtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTxtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(btnReset))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah)
                            .addComponent(jTxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtjudulActionPerformed

    private void jTxtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidActionPerformed

    private void jTxtgenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtgenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtgenreActionPerformed

    private void jTxtpenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtpenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtpenulisActionPerformed

    private void jTxtpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtpenerbitActionPerformed

    private void jTxtlokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtlokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtlokasiActionPerformed

    private void jTxtstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtstockActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        dc.insert();
        dc.isiGenre();
        dc.isitabel();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        dc.isiGenre();
        dc.isitabel();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        dc.update();
        dc.isiGenre();
        dc.isitabel();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tabelDatabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDatabukuMouseClicked
        // TODO add your handling code here:
        int baris = tabelDatabuku.getSelectedRow();
        jTxtid.setText(tabelDatabuku.getValueAt(baris, 0).toString());
        jTxtjudul.setText(tabelDatabuku.getValueAt(baris, 1).toString());
        jTxtgenre.setText(tabelDatabuku.getValueAt(baris, 2).toString());
        jTxtpenulis.setText(tabelDatabuku.getValueAt(baris, 3).toString());
        jTxtpenerbit.setText(tabelDatabuku.getValueAt(baris, 4).toString());
        jTxtlokasi.setText(tabelDatabuku.getValueAt(baris, 5).toString());
        jTxtstock.setText(tabelDatabuku.getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tabelDatabukuMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isiGenre();
        dc.isitabel();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        dc.isiGenre();
        dc.search();
    }//GEN-LAST:event_btnCariActionPerformed

    private void listgenreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listgenreItemStateChanged
        // TODO add your handling code here:
        // memastikan bahwa event yg terjadi adalah pemilihan genre
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            dc.searchGenre();
        }
    }//GEN-LAST:event_listgenreItemStateChanged

    private void jTextsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextsearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        jTxtid.setText("");
        jTxtjudul.setText("");
        jTxtgenre.setText("");
        jTxtpenulis.setText("");
        jTxtpenerbit.setText("");
        jTxtlokasi.setText("");
        jTxtstock.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTampil;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextsearch;
    private javax.swing.JTextField jTxtgenre;
    private javax.swing.JTextField jTxtid;
    private javax.swing.JTextField jTxtjudul;
    private javax.swing.JTextField jTxtlokasi;
    private javax.swing.JTextField jTxtpenerbit;
    private javax.swing.JTextField jTxtpenulis;
    private javax.swing.JTextField jTxtstock;
    private javax.swing.JComboBox<String> listgenre;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JTable tabelDatabuku;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelDatabuku() {
        return tabelDatabuku;
    }

    public void setTabelDatabuku(JTable tabelDatabuku) {
        this.tabelDatabuku = tabelDatabuku;
    }

    public JTextField getjTxtgenre() {
        return jTxtgenre;
    }

    public void setjTxtgenre(JTextField jTxtgenre) {
        this.jTxtgenre = jTxtgenre;
    }

    public JTextField getjTxtid() {
        return jTxtid;
    }

    public void setjTxtid(JTextField jTxtid) {
        this.jTxtid = jTxtid;
    }

    public JTextField getjTxtjudul() {
        return jTxtjudul;
    }

    public void setjTxtjudul(JTextField jTxtjudul) {
        this.jTxtjudul = jTxtjudul;
    }

    public JTextField getjTxtlokasi() {
        return jTxtlokasi;
    }

    public void setjTxtlokasi(JTextField jTxtlokasi) {
        this.jTxtlokasi = jTxtlokasi;
    }

    public JTextField getjTxtpenerbit() {
        return jTxtpenerbit;
    }

    public void setjTxtpenerbit(JTextField jTxtpenerbit) {
        this.jTxtpenerbit = jTxtpenerbit;
    }

    public JTextField getjTxtpenulis() {
        return jTxtpenulis;
    }

    public void setjTxtpenulis(JTextField jTxtpenulis) {
        this.jTxtpenulis = jTxtpenulis;
    }

    public JTextField getjTxtstock() {
        return jTxtstock;
    }

    public void setjTxtstock(JTextField jTxtstock) {
        this.jTxtstock = jTxtstock;
    }

    public JComboBox<String> getListgenre() {
        return listgenre;
    }

    public JTextField getjTextsearch() {
        return jTextsearch;
    }

    public JComboBox<String> getSearchBy() {
        return searchBy;
    }
    
    
    
    
}

